<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="renderer" content="webkit">
<meta name="applicable-device" content="pc,mobile">
<title>速成(SuCms)影视管理程序-Power by SuCms</title>
<meta name="keywords" content="速成(SuCms)影视管理程序" />
<meta name="description" content="速成(SuCms)影视管理程序" />
<link href="/skin/css/style.css" rel="stylesheet">
<script>var sitePath='upload/'</script>
<script src="/skin/js/jquery-1.4.4.min.js"></script>
<script src="/skin/js/common.js"></script>
<script src="/skin/js/function.js"></script>
<script src="/skin/js/jquery.lazyload.js"></script>
<link href="/favicon.ico" type="image/x-icon" rel="icon">
<link href="/favicon.ico" type="image/x-icon" rel="shortcut icon">
<!--[if lt IE 9]>
<script src="/skin/js/html5shiv.min.js"></script>
<script src="/skin/js/respond.min.js"></script>
<![endif]-->
<script src="/skin/js/jquery.superslide.js" type="text/javascript"></script>
</head>
<body>
<div class="header-all">
  <div class="top clearfix">
    <ul class="logo"><a href="http://localhost"><i class="logobg"></i></a></ul>
    <ul class="top-nav">
      <li><a class="now" href="/upload/">首页</a></li>
      
      
      <li class="" _t_nav="topnav-1"><a href="/upload/sucms-list/?1.html">电影<i class="sjbgs"></i><i class="sjbgx"></i></a></li>
      
      
      
      <li class="" _t_nav="topnav-2"><a href="/upload/sucms-list/?2.html">电视剧<i class="sjbgs"></i><i class="sjbgx"></i></a></li>
      
      
      
      <li><a href="/upload/sucms-list/?3.html">综艺</a></li>
      
      
      
      <li><a href="/upload/sucms-list/?4.html">动漫</a></li>
      
      
      <li><a href="/upload/topic/?1.html">专题</a></li>
      <li class="" _t_nav="topnav-news"><a href="/upload/news/">新闻<i class="sjbgs"></i><i class="sjbgx"></i></a></li>
      <li><a href="/plus/gbook.php">留言</a></li>
    </ul>
    <ul class="search so">
      <form name="formsearch" id="formsearch" action='/search.php' method="post"  target="_self" autocomplete="off">
          <input class="input" name="searchword" type="text" id="keyword" placeholder="请输入影片或演员名" />
          <div class="so-key"><a href='/upload/search.php?searchword=%E5%85%B3%E9%94%AE%E8%AF%8DA'>关键词A</a> <a href='/upload/search.php?searchword=%E5%85%B3%E9%94%AE%E8%AF%8DB'>关键词B</a> <a href='/upload/search.php?searchword=%E5%85%B3%E9%94%AE%E8%AF%8DC'>关键词C</a> <a href='/upload/search.php?searchword=%E5%85%B3%E9%94%AE%E8%AF%8DD'>关键词D</a> <a href='/upload/search.php?searchword=%E5%85%B3%E9%94%AE%E8%AF%8DD'>关键词D</a> </div>
          <input class="imgbt" type="submit" value=""/>
      </form>
    </ul>
    <ul class="nav-qt aa">
      <li class="bb"><a href="javascript:void(0)" onMouseOver="$MH.showHistory(1);"><i class="jl"></i>观看历史</a>
      <div class="cc">
	  <script type="text/javascript" src="/skin/js/history.js"></script>
          <script type="text/javascript">$MH.limit=10;$MH.WriteHistoryBox(180,170,'font');$MH.recordHistory({name:'{playpage:name}',link:'{playpage:url}',pic:'{playpage:pic}'})</script></div>
      </li>
      <li class="bb"><strong class="ma"><i class="mabg"></i>手机观看</strong>
      <div class="cc maw"><i class="ewmbg"></i><p>扫描二维码用手机观看</p></div>  
      </li>
    </ul>
    <ul class="sj-search">
      <li class="sbtn2"><i class="sjbg-search"></i></li>
    </ul>
    <ul class="sj-nav">
      <li class="sbtn1"><i class="sjbg-nav"></i></li>
    </ul>
    <ul class="sj-navhome">
      <li><a href="/upload/"><i class="sjbg-home"></i></a></li>
    </ul>  
  </div>
  <div class="nav-down clearfix">
  
  
  <div id="topnav-1" class="nav-down-1" style="display:none;" _t_nav="topnav-1">
    <div class="nav-down-2 clearfix">
    <ul>
           
      <li><a href="/upload/sucms-list/?5.html">动作片</a></li>
           
      <li><a href="/upload/sucms-list/?6.html">喜剧片</a></li>
           
      <li><a href="/upload/sucms-list/?7.html">爱情片</a></li>
           
      <li><a href="/upload/sucms-list/?8.html">科幻片</a></li>
           
      <li><a href="/upload/sucms-list/?9.html">剧情片</a></li>
           
      <li><a href="/upload/sucms-list/?10.html">恐怖片</a></li>
           
      <li><a href="/upload/sucms-list/?11.html">战争片</a></li>
      
    </ul>
    </div>
  </div>
  
  
  
  <div id="topnav-2" class="nav-down-1" style="display:none;" _t_nav="topnav-2">
    <div class="nav-down-2 clearfix">
    <ul>
           
      <li><a href="/upload/sucms-list/?12.html">大陆剧</a></li>
           
      <li><a href="/upload/sucms-list/?13.html">港台剧</a></li>
           
      <li><a href="/upload/sucms-list/?14.html">日韩剧</a></li>
           
      <li><a href="/upload/sucms-list/?15.html">欧美剧</a></li>
      
    </ul>
    </div>
  </div>
  
  
  
  
  
  
  <div id="topnav-news" class="nav-down-1" style="display:none;" _t_nav="topnav-news">
    <div class="nav-down-2 clearfix">
    <ul>
           
      <li><a href="/upload/articlelist/?16.html">影视资讯</a></li>
           
      <li><a href="/upload/articlelist/?17.html">剧情介绍</a></li>
      
    </ul>
    </div>
  </div>
  <div id="sj-nav-1" class="nav-down-1 sy1 sj-noover" style="display:none;" _s_nav="sj-nav-1">
    <div class="nav-down-2 sj-nav-down-2 clearfix">
    <ul> 
      <li><a href="/upload/">首页</a></li>
        
      <li><a href="/upload/sucms-list/?1.html">电影</a></li>
        
      <li><a href="/upload/sucms-list/?2.html">电视剧</a></li>
        
      <li><a href="/upload/sucms-list/?3.html">综艺</a></li>
        
      <li><a href="/upload/sucms-list/?4.html">动漫</a></li>
        
      <li><a href="/upload/sucms-list/?5.html">动作片</a></li>
        
      <li><a href="/upload/sucms-list/?6.html">喜剧片</a></li>
        
      <li><a href="/upload/sucms-list/?7.html">爱情片</a></li>
        
      <li><a href="/upload/sucms-list/?8.html">科幻片</a></li>
        
      <li><a href="/upload/sucms-list/?9.html">剧情片</a></li>
        
      <li><a href="/upload/sucms-list/?10.html">恐怖片</a></li>
        
      <li><a href="/upload/sucms-list/?11.html">战争片</a></li>
        
      <li><a href="/upload/sucms-list/?12.html">大陆剧</a></li>
        
      <li><a href="/upload/sucms-list/?13.html">港台剧</a></li>
        
      <li><a href="/upload/sucms-list/?14.html">日韩剧</a></li>
        
      <li><a href="/upload/sucms-list/?15.html">欧美剧</a></li>
    
      <li><a href="/upload/topic/?1.html">专题</a></li>
      <li><a href="/upload/news/">新闻</a></li>
      <li><a href="/plus/gbook.php">留言</a></li>
    </ul>
    </div>
  </div>
  <div id="sj-nav-search" class="nav-down-1 sy2 sj-noover" style="display:none;" _t_nav1="sj-nav-search">
    <div class="nav-down-2 sj-nav-down-search clearfix">
    <form name="formsearch" id="formsearch" action='/upload/search.php' method="post"  target="_self" autocomplete="off">
          <input class="input" name="searchword" type="text" id="keyword" placeholder="输入关键词"/>
          <input class="imgbt" type="submit" value="搜索"/>
      </form>
    </div>
  </div>
</div>
</div>
<div class="topone clearfix"></div>
<div class="channel-focus">
  <div class="channel-silder layout">
    <ul class="channel-silder-cnt">
    
    </ul>
    <ul class="channel-silder-nav">
    
    </ul>
  </div>
</div>
<script type="text/javascript">
	jQuery(".channel-silder").slide({ 
		titCell:".channel-silder-nav li",
		mainCell:".channel-silder-cnt",
		delayTime:800,
		triggerTime:0,
		interTime:5000,
		pnLoop:false,
		autoPage:false,
		autoPlay:true
	});
</script>
<div class="main">
	<div class="index-area clearfix">
    <h1 class="title index-color">推荐影片</h1>
    <ul>
    
    </ul>
    </div>

	<div class="index-area clearfix">
    <h1 class="title index-color">
      <span class="hitkey kp">
      <a href="/upload/sucms-list/?1.html">更多&raquo;</a>
      </span>
      电影</h1>
    <ul>
    
    </ul>
    </div>
    
	<div class="index-area clearfix">
    <h1 class="title index-color">
      <span class="hitkey kp">
      <a href="/upload/sucms-list/?2.html">更多&raquo;</a>
      </span>
      电视剧</h1>
    <ul>
    
    </ul>
    </div>
    
	<div class="index-area clearfix">
    <h1 class="title index-color">
      <span class="hitkey kp">
      <a href="/upload/sucms-list/?3.html">更多&raquo;</a>
      </span>
      综艺</h1>
    <ul>
    
    </ul>
    </div>
    
	<div class="index-area clearfix">
    <h1 class="title index-color">
      <span class="hitkey kp">
      <a href="/upload/sucms-list/?4.html">更多&raquo;</a>
      </span>
      动漫</h1>
    <ul>
    
    </ul>
    </div>
    
</div>
<div class="ylink clearfix">
    
      <a href="http://www.sucms.org" target="_blank">速成影视管理系统</a>
    
</div>
<div class="footer clearfix">
Copyright &#169; 2015 sucms. 速成电影管理系统 版权所有 {sucms:runinfo}   <p class="footer-bg"><span class="bg"></span></p>
</div>
<div class="gotop"><a class="gotopbg" href="javascript:;" title="返回顶部"></a></div>
</body>
</html>
